Algoritmo AREA_RECTANGULO
	Escribir 'CÁLCULO DEL ÁREA DE UN RECTÁNGULO'
	Escribir 'INTRODUCIR EL ALTURA'
	Definir ALTURA, BASE, AREA Como REAL
	Leer ALTURA
	Escribir 'INTRODUCIR LA BASE'
	Leer BASE
	AREA<-BASE * ALTURA
	Escribir 'EL ÁREA DEL RECTÁNGULO ES: ' , AREA	
FinAlgoritmo
