/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author diego
 */
public class PanelResultados extends javax.swing.JPanel {

    /**
     * Creates new form PanelResultados
     */
    public PanelResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbLimpiar1 = new javax.swing.JButton();
        jlTotal1 = new javax.swing.JLabel();
        jtPagar1 = new javax.swing.JTextField();
        jbCalcular1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        setLayout(new java.awt.GridLayout(2, 3));
        add(jLabel3);
        add(jLabel4);

        jbLimpiar1.setText("Limpiar");
        add(jbLimpiar1);

        jlTotal1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jlTotal1.setText("Total a pagar");
        add(jlTotal1);

        jtPagar1.setEditable(false);
        jtPagar1.setForeground(new java.awt.Color(51, 153, 255));
        add(jtPagar1);

        jbCalcular1.setText("Calcular");
        add(jbCalcular1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbCalcular1;
    private javax.swing.JButton jbLimpiar1;
    private javax.swing.JLabel jlTotal1;
    private javax.swing.JTextField jtPagar1;
    // End of variables declaration//GEN-END:variables
}
